config/routes.rb
Douban::Application.routes.draw do
  post "welcome/login"
  get "welcome/index"
  get "welcome/logout"

  resources :dailyposts

  resources :dailynotes

  resources :posts

  resources :topics do
    resources :posts
  end

  resources :groups do
    resources :topics
  end

  resources :photobooks

  resources :users

  root :to => 'welcome#index'

end

app/models/dailypost.rb
#encoding: utf-8
#日记的跟帖Model
class Dailypost < ActiveRecord::Base
  attr_accessible :content, :dailynote_id, :image
  belongs_to :dailynote
end

app/controllers/dailyposts_controller.rb
class DailypostsController < ApplicationController
  # GET /dailyposts
  # GET /dailyposts.json
  def index
    @dailyposts = Dailypost.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dailyposts }
    end
  end

  # GET /dailyposts/1
  # GET /dailyposts/1.json
  def show
    @dailypost = Dailypost.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dailypost }
    end
  end

  # GET /dailyposts/new
  # GET /dailyposts/new.json
  def new
    @dailypost = Dailypost.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dailypost }
    end
  end

  # GET /dailyposts/1/edit
  def edit
    @dailypost = Dailypost.find(params[:id])
  end

  # POST /dailyposts
  # POST /dailyposts.json
  def create
    @dailypost = Dailypost.new(params[:dailypost])

    respond_to do |format|
      if @dailypost.save
        format.html { redirect_to @dailypost, notice: 'Dailypost was successfully created.' }
        format.json { render json: @dailypost, status: :created, location: @dailypost }
      else
        format.html { render action: "new" }
        format.json { render json: @dailypost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dailyposts/1
  # PUT /dailyposts/1.json
  def update
    @dailypost = Dailypost.find(params[:id])

    respond_to do |format|
      if @dailypost.update_attributes(params[:dailypost])
        format.html { redirect_to @dailypost, notice: 'Dailypost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dailypost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dailyposts/1
  # DELETE /dailyposts/1.json
  def destroy
    @dailypost = Dailypost.find(params[:id])
    @dailypost.destroy

    respond_to do |format|
      format.html { redirect_to dailyposts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dailyposts_helper.rb
module DailypostsHelper
end

app/views/dailyposts/_form.html.erb
<%= form_for @dailypost, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :dailynote_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :dailynote_id, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                dailyposts_path, :class => 'btn' %>
  </div>
<% end %>

app/views/dailyposts/edit.html.erb
<%- model_class = Dailypost -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dailyposts/index.html.erb
<%- model_class = Dailypost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:dailynote_id) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @dailyposts.each do |dailypost| %>
      <tr>
        <td><%= link_to dailypost.id, dailypost_path(dailypost) %></td>
        <td><%= dailypost.dailynote_id %></td>
        <td><%= dailypost.content %></td>
        <td><%= dailypost.image %></td>
        <td><%=l dailypost.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_dailypost_path(dailypost), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      dailypost_path(dailypost),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_dailypost_path,
            :class => 'btn btn-primary' %>

app/views/dailyposts/new.html.erb
<%- model_class = Dailypost -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/dailyposts/show.html.erb
<%- model_class = Dailypost -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:dailynote_id) %>:</strong></dt>
  <dd><%= @dailypost.dailynote_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @dailypost.content %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @dailypost.image %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              dailyposts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_dailypost_path(@dailypost), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              dailypost_path(@dailypost),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>