config/routes.rb
Douban::Application.routes.draw do
  post "welcome/login"
  get "welcome/index"
  get "welcome/logout"

  resources :dailyposts

  resources :dailynotes

  resources :posts

  resources :topics do
    resources :posts
  end

  resources :groups do
    resources :topics
  end

  resources :photobooks

  resources :users

  root :to => 'welcome#index'

end

app/models/topic.rb
#encoding: utf-8
# 这是话题的Model,每个讨论组 group 可以创建和管理话题
class Topic < ActiveRecord::Base
  attr_accessible :description,:link, :title,:group_id,:user_id,:attachment_id,:image
  belongs_to :group
  has_many :posts
  belongs_to :user
  belongs_to :attachment
  #before_save :set_user
  
  
  def save_image(file)
    if !file.nil?
        @attachment = Attachment.new
        rename =  @attachment.save_att(file) 
        @attachment.save
        self.attachment_id = @attachment.id
        self.image = rename
        return rename
    end # end if end # end if
  end



  private
  def set_user
    if session[:user_id]
      self.user_id = session[:user_id]
    end
  end


end

app/controllers/topics_controller.rb
#encoding: utf-8
class TopicsController < ApplicationController
  layout "main"
  # GET /topics
  # GET /topics.json
  def index
    @group_id = params[:group_id]
    logger.info "the group id is : #{@group_id}"
    if @group_id 
      @topics = Topic.where(:group_id => params[:group_id])
      @group = Group.find(@group_id)
    else
      @topics = Topic.all
    end
    #logger.info "the topics has #{@topics}"

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # 根据group_id 获得改组下的所有话题
  def group
    @topics = Topic.find_by_group_id(params[:group_id])
	respond_to do |format|
	  format.html  # grouptopic.html.erb
	  format.json {render json: @topics}
	end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @group_id = params[:group_id]
    @topic = Topic.new
    unless @group_id.nil?
      @topic.group_id = @group_id
      @group = Group.find(@group_id)
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
    @group = @topic.group
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])
    @topic.user_id = session[:user_id]
    @group_id = params[:group_id]
    if @group_id
      @group = Group.find(@group_id)
    end
    logger.info ("the image is #{params[:topic][:image]}")
    rename = @topic.save_image(params[:topic][:image])
    @topic.image = rename
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])
    @topic.user_id = session[:user_id]
    @group_id = params[:topic][:group_id]
    if @group_id
      @group = Group.find(@group_id)
    end
    logger.info ("the image is #{params[:topic][:image]}")
    if params[:topic][:image]
      rename = @topic.save_image(params[:topic][:image])
    else
      rename = @topic.image
    end
    respond_to do |format|
      if @topic.update_attributes(:image=>rename,:group_id=>@group_id,:user_id=>session[:user_id],:title=>params[:topic][:title],
                                 :description=>params[:topic][:description])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    #logger.info "=========================#{@topic}"
    @group_id = @topic.group_id || 1
    #logger.info "===========================#{@group_id}"
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to group_topics_path(@group_id) }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= form_for @topic, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.number_field :group_id, :class => 'number_field',:type=>'hidden' %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit '创建', :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("返回")),
                group_topics_path(@topic.group_id), :class => 'btn' %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/topics/group.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:link) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:group_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= link_to topic.id, topic_path(topic) %></td>
        <td><%= topic.title %></td>
        <td><%= topic.image %></td>
        <td><%= topic.link %></td>
        <td><%= topic.description %></td>
        <td><%= topic.group_id %></td>
        <td><%=l topic.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_topic_path(topic), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      topic_path(topic),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_topic_path,
            :class => 'btn btn-primary' %>

app/views/topics/index.html.erb
<%- model_class = Topic -%>
<div class="page-header">
  <h1><%= title = @group && @group.name %>讨论组---话题</h1>
</div>
<div class="main box" style="margin-bottom:20px;">
<% @topics.each do |topic| %>
<div class="topic">
  <div class="topic_header">
    <h1><%= link_to topic.title,topic_path(topic) %></h1>
  </div>
  <div class="topic_content">
    <p><%= sanitize topic.description %></p>
  </div>
  <div class="topic_info">
   <div class="topic_tool">
          <%= link_to t('.edit', :default => t("编辑")),
                      edit_topic_path(topic) %>
          <%= link_to t('.destroy', :default => t("删除")),
                      topic_path(topic),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
   </div>
  </div>
</div>
<% end %>
</div>

<%= link_to t('.new', :default => t("新建话题")),
            new_group_topic_path(@group_id) %>

app/views/topics/new.html.erb
<%- model_class = Topic -%>
<div class="main box" style="margin-bottom:20px;">
  <div class="topic">
    <div class="topic_header">
      <h1><%=@group.name%>讨论组---新增话题</h1>
    </div>
    <div class="typecho-post-area">
      <%= form_for @topic,:multipart=>true do |f| %>
        <p>标题：</p>
        <%= f.text_field :title, {:class => 'text title',:style=>"width:540px;"} %>
        <%=f.text_field :group_id,{:type=>"hidden",:value=>"#{@group.id}"}%>
        <p>内容：</p>
        <%= f.text_area :description, {:class => 'title',:style=>"width:540px;height:80px"} %>
        <p>图片:</p>
        <%= f.file_field :image, {:class=>"file_field"} %>
       <div class="comment-submit" style="margin-top:10px;">
         <%= submit_tag "发布", :class=>"submit"%>&nbsp;&nbsp;
         <%= link_to "返回",group_topics_path(@group),:class=>"sumbit"%>
       </div>
      <% end %>
    </div><!-- end of  typecho-post-area -->
  </div><!-- div topic -->
</div>

app/views/topics/show.html.erb
<%- model_class = Topic -%>
<div class="page-header">
 <p class="lead">讨论组：<%= @topic.group && @topic.group.name %></p>
</div>
<div class="main box" style="margin-bottom:20px;">
<div class="topic">
  <div class="topic_header">
    <h1><%= @topic.title %></h1>
  </div>
  <div class="topic_content">
    <p><%= sanitize @topic.description %></p>
  </div>
  <div class="topic_content">
    <p><%= image_tag @topic.image,{:style=>"width:540px;height:300px"} %></p>
  </div>
  <div class="topic_info">
   <div class="topic_tool">
    <a href="#">顶贴</a> <a href="#">转发</a>
   </div>
  </div>
</div>
</div>

<div class="main radius" style="margin-top:20px;">
  <div class="reply_list" style="padding:10px">
    <div style="padding:5px 0px; margin-bottom:5px;text-align:center;">
      已有<%=@topic.posts.count%> 条回帖
    </div>
    <ol class="comment-list">
       <% @topic.posts.each do |post| %>
      <div class="comment-item">
         <div class="content">
           <p><span class="author"><%= post.user && post.user.name%>:</span>  <%=sanitize post.content %></p>
         </div>
      </div>
       <% end %>
    </ol>
  </div>
</div>
<div class="main radius reply_box" style="margin-top:20px">
  <div style="color:#A8B1BA;padding:10px;">
     <span> 您的回帖 </span>
   </div>
   <div class="respond" style="padding:0 10px 10px 10px">
    <%= form_tag({:controller =>"posts",:action => "create"}, :html =>{ :class => 'form-horizontal'}) do  %>
      <%= text_field 'post', "topic_id", {:type=>'hidden',:value=>"#{@topic.id}"}%>
    <div class="controls">
      <%= text_area :post,"content", {:class=>"textarea",:style=>"width:540px;height:80px" } %>
    </div>
    <div class="comment-submit" style="margin-top:10px;">
      <%= submit_tag "提交", :class=>"submit"%>
    </div>
   <% end %>
    </div>

   </div>
</div>