config/routes.rb
Douban::Application.routes.draw do
  post "welcome/login"
  get "welcome/index"
  get "welcome/logout"

  resources :dailyposts

  resources :dailynotes

  resources :posts

  resources :topics do
    resources :posts
  end

  resources :groups do
    resources :topics
  end

  resources :photobooks

  resources :users

  root :to => 'welcome#index'

end

app/models/group.rb
#encoding: utf-8
class Group < ActiveRecord::Base
  attr_accessible :icon, :introduction, :label, :name
  has_many :user_groups
  has_many :users
end

app/controllers/groups_controller.rb
#encoding: utf-8
class GroupsController < ApplicationController
  layout "main"
  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
    @title = "讨论组"
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @groups }
    end
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @group = Group.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/new
  # GET /groups/new.json
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @group }
    end
  end

  # GET /groups/1/edit
  def edit
    @group = Group.find(params[:id])
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render json: @group, status: :created, location: @group }
      else
        format.html { render action: "new" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /groups/1
  # PUT /groups/1.json
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group = Group.find(params[:id])
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for @group, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :introduction, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :introduction, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :icon, :class => 'control-label' %>
    <div class="controls">
      <%= image_tag @group.icon %> <p>
	  <%= f.file_field :icon, :class => 'text_field' %> 
    </div>
  </div>
  <div class="control-group">
    <%= f.label :label, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :label, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="grid-16-8 clearfix">
  <div class="article">
   <div class="group-list">
     <% @groups.each do |group| %>
    <div class="result">
      <div class="pic">
      </div>
      <div class="content">
        <div class="group-title">
          <h3><%= link_to group.name, group_topics_path(group) %></h3>
        </div>
        <div class="info"></div>
        <div><p><%= sanitize group.introduction %></p></div>
      </div>
    </div>
     <% end %>
</div>
</div>
</div>

<%= link_to t('.new', :default => t("新建讨论组")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="main box" style="margin-bottom:20px;">
  <div class="topic">
    <div class="topic_header">
      <h1>新建讨论组</h1>
    </div>
    <div class="typecho-post-area">
      <%= form_for @group,:multipart=>true do |f| %>
        <p>小组名称：</p>
        <%= f.text_field :name, {:class => 'text title',:style=>"width:540px;"} %>
        <p>小组介绍：</p>
        <%= f.text_area :introduction, {:class => 'title',:style=>"width:540px;height:80px"} %>
        <p>小组标签:</p>
        <%= f.text_field :label,{:class=>"text label",:style=>"width:540px;"} %>
        <p>图片:</p>
        <%= f.file_field :icon, {:class=>"file_field"} %>
       <div class="comment-submit" style="margin-top:10px;">
         <%= submit_tag "提交申请", :class=>"submit"%>&nbsp;&nbsp;
         <%= link_to "返回",new_group_path(@group),:class=>"sumbit"%>
       </div>
      <% end %>
    </div><!-- end of  typecho-post-area -->
  </div><!-- div topic -->
</div>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="main box" style="margin-bottom:20px;">
<div class="topic">
  <div class="topic_header">
    <h1><%="新建的讨论组：#{@group.name}" %></h1>
  </div>
  <div class="topic_content">
    <p>小组名：<%= sanitize @group.name %></p>
  </div>
  <div class="topic_content">
    <p>小组简介：<%= sanitize @group.introduction %></p>
  </div>
  <div class="topic_content">
    <p>小组标签：<%= sanitize @group.label %></p>
  </div>
  <div class="topic_content">
    <p>小组图标：<%=image_tag @group.icon,{:style=>"width:40px;height:30px;"} %></p>
  </div>
</div>
</div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("返回")),
              groups_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("编辑")),
              edit_group_path(@group), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("删除")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>