config/routes.rb
Douban::Application.routes.draw do
  post "welcome/login"
  get "welcome/index"
  get "welcome/logout"

  resources :dailyposts

  resources :dailynotes

  resources :posts

  resources :topics do
    resources :posts
  end

  resources :groups do
    resources :topics
  end

  resources :photobooks

  resources :users

  root :to => 'welcome#index'

end

app/models/photobook.rb
class Photobook < ActiveRecord::Base
  attr_accessible :description, :name, :preface
  belongs_to :user
end

app/controllers/photobooks_controller.rb
class PhotobooksController < ApplicationController
  # GET /photobooks
  # GET /photobooks.json
  def index
    @photobooks = Photobook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photobooks }
    end
  end

  # GET /photobooks/1
  # GET /photobooks/1.json
  def show
    @photobook = Photobook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photobook }
    end
  end

  # GET /photobooks/new
  # GET /photobooks/new.json
  def new
    @photobook = Photobook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photobook }
    end
  end

  # GET /photobooks/1/edit
  def edit
    @photobook = Photobook.find(params[:id])
  end

  # POST /photobooks
  # POST /photobooks.json
  def create
    @photobook = Photobook.new(params[:photobook])

    respond_to do |format|
      if @photobook.save
        format.html { redirect_to @photobook, notice: 'Photobook was successfully created.' }
        format.json { render json: @photobook, status: :created, location: @photobook }
      else
        format.html { render action: "new" }
        format.json { render json: @photobook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photobooks/1
  # PUT /photobooks/1.json
  def update
    @photobook = Photobook.find(params[:id])

    respond_to do |format|
      if @photobook.update_attributes(params[:photobook])
        format.html { redirect_to @photobook, notice: 'Photobook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photobook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photobooks/1
  # DELETE /photobooks/1.json
  def destroy
    @photobook = Photobook.find(params[:id])
    @photobook.destroy

    respond_to do |format|
      format.html { redirect_to photobooks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/photobooks_helper.rb
module PhotobooksHelper
end

app/views/photobooks/_form.html.erb
<%= form_for(@photobook) do |f| %>
  <% if @photobook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photobook.errors.count, "error") %> prohibited this photobook from being saved:</h2>

      <ul>
      <% @photobook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :preface %><br />
    <%= f.text_field :preface %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photobooks/edit.html.erb
<h1>Editing photobook</h1>

<%= render 'form' %>

<%= link_to 'Show', @photobook %> |
<%= link_to 'Back', photobooks_path %>

app/views/photobooks/index.html.erb
<h1>Listing photobooks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Preface</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photobooks.each do |photobook| %>
  <tr>
    <td><%= photobook.name %></td>
    <td><%= photobook.description %></td>
    <td><%= photobook.preface %></td>
    <td><%= link_to 'Show', photobook %></td>
    <td><%= link_to 'Edit', edit_photobook_path(photobook) %></td>
    <td><%= link_to 'Destroy', photobook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photobook', new_photobook_path %>

app/views/photobooks/new.html.erb
<h1>New photobook</h1>

<%= render 'form' %>

<%= link_to 'Back', photobooks_path %>

app/views/photobooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @photobook.name %>
</p>

<p>
  <b>Description:</b>
  <%= @photobook.description %>
</p>

<p>
  <b>Preface:</b>
  <%= @photobook.preface %>
</p>


<%= link_to 'Edit', edit_photobook_path(@photobook) %> |
<%= link_to 'Back', photobooks_path %>